config/routes.rb
Rails.application.routes.draw do
  resources :games
  root to: "bets#index"

  resources :users
  resources :games

end

app/models/bet.rb
class Bet < ActiveRecord::Base
  scope :by_round, -> (id){ where(round_id: id) }

  belongs_to :user
  belongs_to :round

  validates_associated :user, :round
  validates :ammount, presence: true
end

app/models/concerns/shared_methods.rb
module SharedMethods
  extend ActiveSupport::Concern


  module ClassMethods
    
    # Sets a target color with different percentages
    def set_color
      case rand(100) + 1 # Gives you the 100%
      when (1..2) then "Green" # 2% chance
      when (3..47) then "Red" # 49% chance
      when (48..100) then "Black" # 49% chance
      end
    end

  end

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :user
  belongs_to :game

  validates_presence_of :user_id, :game_id, :bet
  validates_associated :user, :game
end

app/models/round.rb
class Round < ActiveRecord::Base
  include SharedMethods

  has_many :bets
  has_many :users, through: :bets

  def self.play

    self.transaction do
      winner_color = self.set_color # Roulette result
      user_bet_color = User.set_color # User bet
      match_multiplier = set_multiplier(winner_color)
      round = Round.create(winner: winner_color)

      User.available_to_bet.each do |user|
        current_bet = user.set_current_bet # Saves the current bet in memory (WARNING: It's a Random generated number, use this var instead method)
        user.update(credits: (user.credits - current_bet) )
        bet = Bet.create(round_id: round.id, user_id: user.id, ammount: current_bet, target: user_bet_color)

        # Updates with bonus if gets the same result as Roulette
        if user_bet_color.eql? winner_color
          user_prize = current_bet * match_multiplier
          user.update( credits: ( user.credits + user_prize ) )
        end

        bet.save
      end

    end

  end

  def self.set_multiplier color
    color = "Green" ? 15 : 2
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  include SharedMethods
  scope :available_to_bet, -> { where('credits > 0') }

  has_many :bets
  has_many :rounds, through: :bets

  validates :username, presence: true,  length: { in: 3..255 }, uniqueness: true
  validates :credits, numericality: { greater_than_or_equal_to: 0 }

  # Sets current bet according to weather
  def set_current_bet
    rain_flag = OpenWeatherMapServices.new(city: "Santiago,cl").will_rain_next_week?

    return self.credits if self.credits < 1000   # Current user is all in if credits are lesser than 1000

    if rain_flag
      return ( self.credits * rand(0.04..0.1) ).round
    else
      return ( self.credits * rand(0.08..0.15) ).round
    end
  end

  def bet_on_round id
    bets.where("round_id=#{id}").first
  end

  def self.grant_daily_bonus
    self.transaction do
      all.each do |user|
        user.update(credits: (user.credits + 10000) )
      end
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  def index
    @rounds = Round.all
    @users = User.all
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :current_credits)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bets/index.html.erb
<h1>Current round: <%=  @rounds.last.id %></h1>

<h1>Round History</h1>
<% @rounds.each do |round| %>
  <hr>
  <h4>Round ID: <%= round.id %></h4>
  <h4>Roulette winner color: <%= round.winner %></h4>
  <h4>Bets:</h4>
  <ul>
    <% Bet.by_round(round.id).each do |bet| %>
      <li>
        User <%= bet.user.username %> has bet: <%= bet.ammount %> on <%= bet.target %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsRoulette</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="">
    <%= f.label :credits %>
    <%= f.number_field :credits %>
  </div>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Current credits</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.current_credits %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to 'Start Game', new_game_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>